#!/bin/sh

inactive_sink_index=$(pacmd list-sinks | grep index | awk '!/*/ {print $2}' | head -n 1)

pacmd set-default-sink $inactive_sink_index

# if any media is playing, switch it to the new sink
if [ $(pacmd list-sink-inputs | awk '{print $1; exit}') != 0 ]; then 

    pactl list short sink-inputs | awk '{print $1}' |
    while read line; do
        pacmd move-sink-input $line $inactive_sink_index
    done
fi                                                            

active_port="$(pacmd list-sinks | awk '/\*/ {getline; print;}')"

case $active_port in
    *hdmi*)
        dunstify -r 9998 -t 1000 " Switching to speakers"
        ;;
    *analog*)
        dunstify -r 9998 -t 1000 " Switching to headphones"
        ;;
esac
